version: '3.8'

volumes:
  dados:

networks:
  banco:
  web:
  fila:

services:
  db:
    image: postgres:9.6
    container_name: docker-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234567
      POSTGRES_DB: email_sender
      DB_HOST: db
      REDIS_HOST: queue
    ports:
      - "5438:5432"
    volumes:
      - dados:/var/lib/postgresql/data
    networks:
      - banco

  frontend:
    image: nginx:1.13
    container_name: frontend
    volumes:
      - ./web:/usr/share/nginx/html/
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

    ports:
      - "80:80"
    networks:
      - web
    depends_on:
      - app
  app:
    image: python:3.6
    container_name: app
    volumes:
      - ./app:/app
    working_dir: /app
    command: bash ./app.sh
    networks:
      - banco
      - web
      - fila
    depends_on:
      - db
      - queue
    environment:
      POSTGRES_DB: email_sender
      REDIS_HOST: queue

  queue:
    image: redis:3.2
    container_name: queue
    networks:
      - fila

  worker:
    build: worker
    volumes:
      - ./worker:/worker
    working_dir: /worker
    command: worker.py
    networks:
      - fila
    depends_on:
      - queue
    deploy:
      replicas: 3
    environment:
      REDIS_HOST: queue

